import Foundation

/// Локализация интерфейса на 12 языков.
///
/// Таблица в коде, а не `.lproj` с файлами `.strings`, по одной причине: приложение
/// собирается SwiftPM без Xcode, и ресурсы в рукотворном бандле раскладывать хрупко.
/// Таблица компилируется в бинарник, ничего не теряется при сборке и проверяется тестом
/// на полноту переводов.
public enum Language: String, CaseIterable, Identifiable, Sendable {
    case english = "en"
    case chinese = "zh"
    case hindi = "hi"
    case spanish = "es"
    case french = "fr"
    case arabic = "ar"
    case bengali = "bn"
    case russian = "ru"
    case portuguese = "pt"
    case urdu = "ur"
    case indonesian = "id"
    case german = "de"
    case ukrainian = "uk"
    case italian = "it"
    case swedish = "sv"
    case belarusian = "be"

    public var id: String { rawValue }

    /// Название на своём же языке — так его узнают те, кто на нём читает.
    public var nativeName: String {
        switch self {
        case .english: return "English"
        case .chinese: return "中文"
        case .hindi: return "हिन्दी"
        case .spanish: return "Español"
        case .french: return "Français"
        case .arabic: return "العربية"
        case .bengali: return "বাংলা"
        case .russian: return "Русский"
        case .portuguese: return "Português"
        case .urdu: return "اردو"
        case .indonesian: return "Indonesia"
        case .german: return "Deutsch"
        case .ukrainian: return "Українська"
        case .italian: return "Italiano"
        case .swedish: return "Svenska"
        case .belarusian: return "Беларуская"
        }
    }

    /// Арабский и урду пишутся справа налево — интерфейс обязан зеркалиться.
    public var isRightToLeft: Bool {
        self == .arabic || self == .urdu
    }

    /// Язык системы, если он среди поддерживаемых, иначе английский.
    public static var systemDefault: Language {
        for code in Locale.preferredLanguages {
            let base = String(code.prefix(2)).lowercased()
            if let match = Language(rawValue: base) { return match }
        }
        return .english
    }
}

/// Ключи всех строк интерфейса.
public enum S: String, CaseIterable, Sendable {
    // Состояния
    case stopped, playing, silent, noSignal, captureStopped

    // Кнопки
    case start, stop, quit, settings, hideSettings, diagnostics, hideDiagnostics
    case copy, applyRestart, openPrivacy, searchDevices, useFound, addManually, refresh

    // Показатели
    case packetsPerSecond, totalPackets, source, destination, processing

    // Настройки
    case whereToSend, port, targetsPlaceholder, behaviour, launchAtLogin
    case spectrumInMenuBar, originalBehaviour, originalBehaviourNote, language
    case processingFixed, processingOriginal, notSet

    // Режимы отправки
    case modeTargetList, modeBroadcastLAN, modeBroadcastSubnet, modeMulticast

    // Ленты
    case devices, noDevicesFound, searchingDevices, deviceIdle, deviceReceiving
    case deviceNotReceiving, deviceUnknown, manualAddressPlaceholder

    // Первый запуск и разрешения
    case welcomeTitle, welcomeBody, permissionTitle, permissionBody

    // Диагностика
    case diagSystemAudio, diagProcessing, diagSending, diagDevices
    case diagOK, diagWarning, diagFailure, diagUnknown
    case diagNotRunning, diagAllZeroes, diagPermissionAdvice, diagBandsFlowing
    case diagBandsEmpty, diagBandsEmptyAdvice, diagNoTargets, diagNoTargetsAdvice
    case diagNetworkAdvice, diagNotSending, diagAppearsAfterStart
    case diagSource, diagSendingRate, diagDevicesUnchecked, diagDevicesAdvice, diagTitle
    case captureRestarted

    // Управление поверх сцены
    case columnColour, animationOn, animationOff, quality, qualityFull, qualityLight
    case resetColour, tabLook, fromPalette, animationOffNote

    // Обработка звука
    case sensitivity, silenceThreshold, smoothing, bandGrid, windowKind
    case aggregation, agc, resetDefaults, autoStart, autoStartNote
    case sensitivityNote, silenceNote, gridNote
}

/// Переводы. Английский — опорный: если ключа нет в другом языке, берётся он.
public enum L10n {
    @MainActor public static var current: Language = Language.systemDefault

    public static func string(_ key: S, _ language: Language) -> String {
        table[language]?[key] ?? table[.english]?[key] ?? key.rawValue
    }

    @MainActor public static func callAsFunction(_ key: S) -> String {
        string(key, current)
    }

    /// Строка с подстановками. Каждый `%@` по порядку заменяется своим значением.
    ///
    /// Своя подстановка, а не `String(format:)`, по двум причинам: формат тут
    /// всегда `%@`, а чужая строка с лишним `%d` из перевода уронила бы процесс.
    /// Лишние значения отбрасываются, недостающие оставляют `%@` на месте —
    /// перевод с потерянной подстановкой должен быть заметен, а не тих.
    public static func string(_ key: S, _ language: Language, _ values: [String]) -> String {
        var result = string(key, language)
        for value in values {
            guard let range = result.range(of: "%@") else { break }
            result.replaceSubrange(range, with: value)
        }
        return result
    }

    public static let table: [Language: [S: String]] = [

        .english: [
            .stopped: "Stopped", .playing: "Sound is flowing", .silent: "Silence",
            .noSignal: "No signal", .captureStopped: "Capture stopped",
            .start: "Start", .stop: "Stop", .quit: "Quit", .settings: "Settings",
            .hideSettings: "Hide settings", .diagnostics: "Diagnostics",
            .hideDiagnostics: "Hide diagnostics", .copy: "Copy",
            .applyRestart: "Apply and restart", .openPrivacy: "Open privacy settings",
            .searchDevices: "Search for strips", .useFound: "Use found addresses",
            .addManually: "Add", .refresh: "Refresh",
            .packetsPerSecond: "packets/s", .totalPackets: "total", .source: "Source",
            .destination: "Sending to", .processing: "Processing",
            .whereToSend: "Where to send", .port: "Port",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Behaviour", .launchAtLogin: "Launch at login",
            .spectrumInMenuBar: "Spectrum in the menu bar",
            .originalBehaviour: "Processing as in the original",
            .originalBehaviourNote: "Restores the Windows version behaviour entirely — for comparison.",
            .language: "Language", .processingFixed: "improved",
            .processingOriginal: "as in the original", .notSet: "not set",
            .modeTargetList: "List of addresses", .modeBroadcastLAN: "Broadcast to network",
            .modeBroadcastSubnet: "Broadcast to subnet", .modeMulticast: "Multicast",
            .devices: "Strips", .noDevicesFound: "None found yet",
            .searchingDevices: "Searching…", .deviceIdle: "waiting for signal",
            .deviceReceiving: "receiving from us", .deviceNotReceiving: "not receiving",
            .deviceUnknown: "not asked yet",
            .manualAddressPlaceholder: "Address of a strip",
            .welcomeTitle: "Sound spectrum onto your strips",
            .welcomeBody: "The system will ask for two permissions: recording system audio and local network access. The audio itself goes nowhere — only 44 bytes of spectrum per frame are sent.",
            .permissionTitle: "Audio is being read, but it is all zeroes",
            .permissionBody: "That usually means permission to record system audio was not granted.",
            .diagSystemAudio: "System audio", .diagProcessing: "Processing",
            .diagSending: "Sending", .diagDevices: "Strips",
            .diagOK: "fine", .diagWarning: "attention", .diagFailure: "not working",
            .diagUnknown: "unknown", .diagNotRunning: "not running",
            .diagAllZeroes: "only zeroes for %@ s",
            .diagPermissionAdvice: "Most likely permission to record system audio was not granted",
            .diagBandsFlowing: "bands are filling", .diagBandsEmpty: "all bands are zero",
            .diagBandsEmptyAdvice: "Either it is quiet now, or the signal never reaches the analysis",
            .diagNoTargets: "no addresses set",
            .diagNoTargetsAdvice: "Enter strip addresses or pick a broadcast mode",
            .diagNetworkAdvice: "Check that the Mac is on the same network as the strips",
            .diagNotSending: "packets are not going out",
            .diagAppearsAfterStart: "appears after start",
            .captureRestarted: "Capture rebuilt",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ pkt/s to %@ addr.",
            .diagDevicesUnchecked: "state not checked",
            .diagDevicesAdvice: "Search for strips to check them",
            .diagTitle: "Auralis — diagnostics",
            .columnColour: "Column colour", .animationOn: "Animation on",
            .animationOff: "Animation off", .quality: "Quality",
            .qualityFull: "Full", .qualityLight: "Light",
            .resetColour: "Reset",
            .tabLook: "Look", .fromPalette: "from palette",
            .animationOffNote: "The scene is not drawn. Packets keep going to the strips.",
            .sensitivity: "Sensitivity", .silenceThreshold: "Silence threshold",
            .smoothing: "Smoothing", .bandGrid: "Band grid", .windowKind: "Analysis window",
            .aggregation: "Band folding", .agc: "Auto gain",
            .resetDefaults: "Restore defaults", .autoStart: "Start capture on launch",
            .autoStartNote: "The app starts sending as soon as it opens.",
            .sensitivityNote: "Manual gain instead of automatic. Useful when the strips breathe on quiet passages.",
            .silenceNote: "Below this level a frame counts as empty and the packet fades out.",
            .gridNote: "WLED — the table baked into the firmware, effects were drawn for it.",
        ],

        .russian: [
            .stopped: "Остановлено", .playing: "Звук идёт", .silent: "Тишина",
            .noSignal: "Нет сигнала", .captureStopped: "Захват остановлен",
            .start: "Запустить", .stop: "Остановить", .quit: "Выход", .settings: "Настройки",
            .hideSettings: "Скрыть настройки", .diagnostics: "Диагностика",
            .hideDiagnostics: "Скрыть диагностику", .copy: "Скопировать",
            .applyRestart: "Применить и перезапустить", .openPrivacy: "Открыть настройки приватности",
            .searchDevices: "Искать ленты", .useFound: "Подставить найденные",
            .addManually: "Добавить", .refresh: "Обновить",
            .packetsPerSecond: "пакетов/с", .totalPackets: "всего", .source: "Источник",
            .destination: "Отправка", .processing: "Обработка",
            .whereToSend: "Куда отправлять", .port: "Порт",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Поведение", .launchAtLogin: "Запускать при входе в систему",
            .spectrumInMenuBar: "Спектр в строке меню",
            .originalBehaviour: "Обработка как в оригинале",
            .originalBehaviourNote: "Возвращает поведение Windows-версии целиком — для сравнения.",
            .language: "Язык", .processingFixed: "исправленная",
            .processingOriginal: "как в оригинале", .notSet: "не задана",
            .modeTargetList: "Списком адресов", .modeBroadcastLAN: "Broadcast по сети",
            .modeBroadcastSubnet: "Broadcast подсети", .modeMulticast: "Multicast",
            .devices: "Ленты", .noDevicesFound: "Пока не найдено",
            .searchingDevices: "Идёт поиск…", .deviceIdle: "ждёт сигнала",
            .deviceReceiving: "принимает от нас", .deviceNotReceiving: "не принимает",
            .deviceUnknown: "ещё не спрашивали",
            .manualAddressPlaceholder: "Адрес ленты",
            .welcomeTitle: "Спектр звука — на ленты",
            .welcomeBody: "Система спросит два разрешения: на запись системного звука и на доступ в локальную сеть. Звук никуда не передаётся — в сеть уходят только 44 байта спектра на кадр.",
            .permissionTitle: "Звук читается, но в нём одни нули",
            .permissionBody: "Обычно это значит, что не выдано разрешение на запись системного звука.",
            .diagSystemAudio: "Системный звук", .diagProcessing: "Обработка",
            .diagSending: "Отправка", .diagDevices: "Ленты",
            .diagOK: "в порядке", .diagWarning: "внимание", .diagFailure: "не работает",
            .diagUnknown: "неизвестно", .diagNotRunning: "не запущена",
            .diagAllZeroes: "одни нули уже %@ с",
            .diagPermissionAdvice: "Скорее всего не выдано разрешение на запись системного звука",
            .diagBandsFlowing: "полосы заполняются", .diagBandsEmpty: "все полосы нулевые",
            .diagBandsEmptyAdvice: "Либо сейчас тишина, либо сигнал не доходит до анализа",
            .diagNoTargets: "адресаты не заданы",
            .diagNoTargetsAdvice: "Укажи адреса лент или выбери широковещательный режим",
            .diagNetworkAdvice: "Проверь, что мак в той же сети, что и ленты",
            .diagNotSending: "пакеты не уходят",
            .diagAppearsAfterStart: "появится после запуска",
            .captureRestarted: "Захват пересобран",
            .diagSource: "%@, %@ Гц", .diagSendingRate: "%@ пак/с на %@ адр.",
            .diagDevicesUnchecked: "состояние не проверялось",
            .diagDevicesAdvice: "Запусти поиск лент, чтобы их проверить",
            .diagTitle: "Auralis — диагностика",
            .columnColour: "Цвет столбиков", .animationOn: "Анимация включена",
            .animationOff: "Анимация выключена", .quality: "Качество",
            .qualityFull: "Полное", .qualityLight: "Лёгкое",
            .resetColour: "Сбросить",
            .tabLook: "Вид", .fromPalette: "из палитры",
            .animationOffNote: "Сцена не рисуется. Пакеты продолжают уходить на ленты.",
            .sensitivity: "Чувствительность", .silenceThreshold: "Порог тишины",
            .smoothing: "Сглаживание", .bandGrid: "Сетка полос", .windowKind: "Окно анализа",
            .aggregation: "Свёртка полос", .agc: "Авторегулировка",
            .resetDefaults: "Вернуть рекомендуемые", .autoStart: "Запускать захват при старте",
            .autoStartNote: "Приложение начинает отправку сразу при открытии.",
            .sensitivityNote: "Ручное усиление вместо автоматического. Нужно, когда лента дышит на тихих местах.",
            .silenceNote: "Ниже этого уровня кадр считается пустым и пакет затухает.",
            .gridNote: "WLED — таблица из самой прошивки, эффекты рисовались под неё.",
        ],

        .chinese: [
            .stopped: "已停止", .playing: "正在接收声音", .silent: "静音",
            .noSignal: "无信号", .captureStopped: "采集已停止",
            .start: "启动", .stop: "停止", .quit: "退出", .settings: "设置",
            .hideSettings: "隐藏设置", .diagnostics: "诊断", .hideDiagnostics: "隐藏诊断",
            .copy: "复制", .applyRestart: "应用并重启", .openPrivacy: "打开隐私设置",
            .searchDevices: "搜索灯带", .useFound: "使用找到的地址",
            .addManually: "添加", .refresh: "刷新",
            .packetsPerSecond: "包/秒", .totalPackets: "总计", .source: "声音来源",
            .destination: "发送至", .processing: "处理方式",
            .whereToSend: "发送目标", .port: "端口",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "行为", .launchAtLogin: "登录时启动",
            .spectrumInMenuBar: "在菜单栏显示频谱",
            .originalBehaviour: "使用原版处理方式",
            .originalBehaviourNote: "完全恢复 Windows 版的行为，便于对比。",
            .language: "语言", .processingFixed: "已改进",
            .processingOriginal: "同原版", .notSet: "未设置",
            .modeTargetList: "地址列表", .modeBroadcastLAN: "广播到网络",
            .modeBroadcastSubnet: "广播到子网", .modeMulticast: "组播",
            .devices: "灯带", .noDevicesFound: "尚未找到",
            .searchingDevices: "搜索中…", .deviceIdle: "等待信号",
            .deviceReceiving: "正在接收", .deviceNotReceiving: "未接收",
            .deviceUnknown: "尚未查询",
            .manualAddressPlaceholder: "灯带地址",
            .welcomeTitle: "把声音频谱送到灯带",
            .welcomeBody: "系统会请求两项权限：录制系统声音和访问局域网。声音本身不会外传——每帧只发送 44 字节的频谱数据。",
            .permissionTitle: "能读取声音，但全是零",
            .permissionBody: "通常表示未授予录制系统声音的权限。",
            .diagSystemAudio: "系统声音", .diagProcessing: "处理",
            .diagSending: "发送", .diagDevices: "灯带",
            .diagOK: "正常", .diagWarning: "注意", .diagFailure: "无法工作",
            .diagUnknown: "未知", .diagNotRunning: "未运行",
            .diagAllZeroes: "已有 %@ 秒全是零",
            .diagPermissionAdvice: "很可能未授予录制系统声音的权限",
            .diagBandsFlowing: "频段有数据", .diagBandsEmpty: "所有频段为零",
            .diagBandsEmptyAdvice: "要么现在很安静，要么信号没有到达分析环节",
            .diagNoTargets: "未设置目标地址",
            .diagNoTargetsAdvice: "请填写灯带地址或选择广播模式",
            .diagNetworkAdvice: "请确认 Mac 与灯带在同一网络",
            .diagNotSending: "数据包没有发出",
            .diagAppearsAfterStart: "启动后显示",
            .captureRestarted: "采集已重建",
            .diagSource: "%@，%@ 赫兹", .diagSendingRate: "%@ 包/秒 发往 %@ 个地址",
            .diagDevicesUnchecked: "状态未检查",
            .diagDevicesAdvice: "搜索灯带以进行检查",
            .diagTitle: "Auralis — 诊断",
            .columnColour: "柱状图颜色", .animationOn: "动画已开启",
            .animationOff: "动画已关闭", .quality: "画质",
            .qualityFull: "完整", .qualityLight: "轻量",
            .resetColour: "重置",
            .tabLook: "外观", .fromPalette: "取自配色",
            .animationOffNote: "场景不再绘制。数据包仍在发往灯带。",
            .sensitivity: "灵敏度", .silenceThreshold: "静音阈值",
            .smoothing: "平滑", .bandGrid: "频段网格", .windowKind: "分析窗",
            .aggregation: "频段合并", .agc: "自动增益",
            .resetDefaults: "恢复默认", .autoStart: "启动时开始采集",
            .autoStartNote: "应用打开后立即开始发送。",
            .sensitivityNote: "手动增益替代自动增益。当灯带在安静段落忽明忽暗时有用。",
            .silenceNote: "低于此电平的帧视为空帧，数据包随之淡出。",
            .gridNote: "WLED — 固件内置的频段表，特效正是为它设计的。",
        ],

        .hindi: [
            .stopped: "रुका हुआ", .playing: "ध्वनि आ रही है", .silent: "सन्नाटा",
            .noSignal: "कोई संकेत नहीं", .captureStopped: "कैप्चर रुका",
            .start: "शुरू करें", .stop: "रोकें", .quit: "बंद करें", .settings: "सेटिंग्स",
            .hideSettings: "सेटिंग्स छिपाएँ", .diagnostics: "निदान",
            .hideDiagnostics: "निदान छिपाएँ", .copy: "कॉपी करें",
            .applyRestart: "लागू करें और पुनः आरंभ करें", .openPrivacy: "गोपनीयता सेटिंग्स खोलें",
            .searchDevices: "स्ट्रिप खोजें", .useFound: "मिले पते इस्तेमाल करें",
            .addManually: "जोड़ें", .refresh: "ताज़ा करें",
            .packetsPerSecond: "पैकेट/से", .totalPackets: "कुल", .source: "स्रोत",
            .destination: "भेजा जा रहा है", .processing: "प्रोसेसिंग",
            .whereToSend: "कहाँ भेजें", .port: "पोर्ट",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "व्यवहार", .launchAtLogin: "लॉगिन पर शुरू करें",
            .spectrumInMenuBar: "मेन्यू बार में स्पेक्ट्रम",
            .originalBehaviour: "मूल संस्करण जैसी प्रोसेसिंग",
            .originalBehaviourNote: "तुलना के लिए Windows संस्करण का व्यवहार पूरी तरह लौटाता है।",
            .language: "भाषा", .processingFixed: "बेहतर",
            .processingOriginal: "मूल जैसा", .notSet: "सेट नहीं",
            .modeTargetList: "पतों की सूची", .modeBroadcastLAN: "नेटवर्क पर ब्रॉडकास्ट",
            .modeBroadcastSubnet: "सबनेट पर ब्रॉडकास्ट", .modeMulticast: "मल्टीकास्ट",
            .devices: "स्ट्रिप", .noDevicesFound: "अभी कोई नहीं मिला",
            .searchingDevices: "खोज जारी…", .deviceIdle: "संकेत का इंतज़ार",
            .deviceReceiving: "हमसे प्राप्त कर रही है", .deviceNotReceiving: "प्राप्त नहीं कर रही",
            .deviceUnknown: "अभी पूछा नहीं",
            .manualAddressPlaceholder: "स्ट्रिप का पता",
            .welcomeTitle: "ध्वनि का स्पेक्ट्रम स्ट्रिप पर",
            .welcomeBody: "सिस्टम दो अनुमतियाँ माँगेगा: सिस्टम ध्वनि रिकॉर्ड करना और लोकल नेटवर्क। ध्वनि कहीं नहीं भेजी जाती — प्रति फ़्रेम केवल 44 बाइट स्पेक्ट्रम जाता है।",
            .permissionTitle: "ध्वनि पढ़ी जा रही है, पर उसमें केवल शून्य हैं",
            .permissionBody: "आमतौर पर इसका मतलब है कि सिस्टम ध्वनि रिकॉर्ड करने की अनुमति नहीं मिली।",
            .diagSystemAudio: "सिस्टम ध्वनि", .diagProcessing: "प्रोसेसिंग",
            .diagSending: "भेजना", .diagDevices: "स्ट्रिप",
            .diagOK: "ठीक है", .diagWarning: "ध्यान दें", .diagFailure: "काम नहीं कर रहा",
            .diagUnknown: "अज्ञात", .diagNotRunning: "चालू नहीं",
            .diagAllZeroes: "%@ सेकंड से केवल शून्य",
            .diagPermissionAdvice: "सबसे संभव है कि सिस्टम ध्वनि की अनुमति नहीं दी गई",
            .diagBandsFlowing: "बैंड भर रहे हैं", .diagBandsEmpty: "सभी बैंड शून्य",
            .diagBandsEmptyAdvice: "या तो अभी शांति है, या संकेत विश्लेषण तक नहीं पहुँच रहा",
            .diagNoTargets: "कोई पता तय नहीं",
            .diagNoTargetsAdvice: "स्ट्रिप के पते डालें या ब्रॉडकास्ट मोड चुनें",
            .diagNetworkAdvice: "जाँचें कि Mac और स्ट्रिप एक ही नेटवर्क पर हैं",
            .diagNotSending: "पैकेट नहीं जा रहे",
            .diagAppearsAfterStart: "शुरू करने पर दिखेगा",
            .captureRestarted: "कैप्चर फिर से बनाया गया",
            .diagSource: "%@, %@ हर्ट्ज़", .diagSendingRate: "%@ पैकेट/से %@ पतों पर",
            .diagDevicesUnchecked: "स्थिति जाँची नहीं गई",
            .diagDevicesAdvice: "जाँचने के लिए स्ट्रिप खोजें",
            .diagTitle: "Auralis — निदान",
            .columnColour: "स्तंभ रंग", .animationOn: "एनिमेशन चालू",
            .animationOff: "एनिमेशन बंद", .quality: "गुणवत्ता",
            .qualityFull: "पूर्ण", .qualityLight: "हल्की",
            .resetColour: "रीसेट",
            .tabLook: "रूप", .fromPalette: "पैलेट से",
            .animationOffNote: "दृश्य नहीं बन रहा। पैकेट स्ट्रिप तक जाते रहते हैं।",
            .sensitivity: "संवेदनशीलता", .silenceThreshold: "मौन सीमा",
            .smoothing: "स्मूथिंग", .bandGrid: "बैंड ग्रिड", .windowKind: "विश्लेषण विंडो",
            .aggregation: "बैंड संयोजन", .agc: "स्वतः गेन",
            .resetDefaults: "डिफ़ॉल्ट लौटाएँ", .autoStart: "शुरू होते ही कैप्चर चालू",
            .autoStartNote: "ऐप खुलते ही भेजना शुरू कर देता है।",
            .sensitivityNote: "स्वतः के बजाय मैनुअल गेन। जब शांत हिस्सों में स्ट्रिप साँस लेती हो तब उपयोगी।",
            .silenceNote: "इस स्तर से नीचे फ्रेम खाली माना जाता है और पैकेट फीका पड़ जाता है।",
            .gridNote: "WLED — फर्मवेयर की अपनी तालिका, प्रभाव उसी के लिए बने थे।",
        ],

        .spanish: [
            .stopped: "Detenido", .playing: "Hay sonido", .silent: "Silencio",
            .noSignal: "Sin señal", .captureStopped: "Captura detenida",
            .start: "Iniciar", .stop: "Detener", .quit: "Salir", .settings: "Ajustes",
            .hideSettings: "Ocultar ajustes", .diagnostics: "Diagnóstico",
            .hideDiagnostics: "Ocultar diagnóstico", .copy: "Copiar",
            .applyRestart: "Aplicar y reiniciar", .openPrivacy: "Abrir ajustes de privacidad",
            .searchDevices: "Buscar tiras", .useFound: "Usar direcciones encontradas",
            .addManually: "Añadir", .refresh: "Actualizar",
            .packetsPerSecond: "paquetes/s", .totalPackets: "total", .source: "Fuente",
            .destination: "Enviando a", .processing: "Procesamiento",
            .whereToSend: "Adónde enviar", .port: "Puerto",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Comportamiento", .launchAtLogin: "Abrir al iniciar sesión",
            .spectrumInMenuBar: "Espectro en la barra de menús",
            .originalBehaviour: "Procesamiento como en el original",
            .originalBehaviourNote: "Restaura por completo el comportamiento de la versión de Windows, para comparar.",
            .language: "Idioma", .processingFixed: "mejorado",
            .processingOriginal: "como el original", .notSet: "sin definir",
            .modeTargetList: "Lista de direcciones", .modeBroadcastLAN: "Difusión a la red",
            .modeBroadcastSubnet: "Difusión a la subred", .modeMulticast: "Multidifusión",
            .devices: "Tiras", .noDevicesFound: "Aún no se encontró ninguna",
            .searchingDevices: "Buscando…", .deviceIdle: "esperando señal",
            .deviceReceiving: "recibiendo de nosotros", .deviceNotReceiving: "no recibe",
            .deviceUnknown: "aún sin consultar",
            .manualAddressPlaceholder: "Dirección de la tira",
            .welcomeTitle: "El espectro del sonido en tus tiras",
            .welcomeBody: "El sistema pedirá dos permisos: grabar el audio del sistema y acceder a la red local. El audio no sale de aquí: solo se envían 44 bytes de espectro por fotograma.",
            .permissionTitle: "Se lee el audio, pero son todo ceros",
            .permissionBody: "Suele significar que no se concedió el permiso para grabar el audio del sistema.",
            .diagSystemAudio: "Audio del sistema", .diagProcessing: "Procesamiento",
            .diagSending: "Envío", .diagDevices: "Tiras",
            .diagOK: "correcto", .diagWarning: "atención", .diagFailure: "no funciona",
            .diagUnknown: "desconocido", .diagNotRunning: "no está en marcha",
            .diagAllZeroes: "solo ceros desde hace %@ s",
            .diagPermissionAdvice: "Lo más probable es que falte el permiso para grabar el audio del sistema",
            .diagBandsFlowing: "las bandas se llenan", .diagBandsEmpty: "todas las bandas a cero",
            .diagBandsEmptyAdvice: "O hay silencio, o la señal no llega al análisis",
            .diagNoTargets: "sin direcciones",
            .diagNoTargetsAdvice: "Indica las direcciones de las tiras o elige un modo de difusión",
            .diagNetworkAdvice: "Comprueba que el Mac esté en la misma red que las tiras",
            .diagNotSending: "los paquetes no salen",
            .diagAppearsAfterStart: "aparece tras iniciar",
            .captureRestarted: "Captura reconstruida",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ paq/s a %@ dir.",
            .diagDevicesUnchecked: "estado sin comprobar",
            .diagDevicesAdvice: "Busca tiras para comprobarlas",
            .diagTitle: "Auralis — diagnóstico",
            .columnColour: "Color de las barras", .animationOn: "Animación activada",
            .animationOff: "Animación desactivada", .quality: "Calidad",
            .qualityFull: "Completa", .qualityLight: "Ligera",
            .resetColour: "Restablecer",
            .tabLook: "Aspecto", .fromPalette: "de la paleta",
            .animationOffNote: "La escena no se dibuja. Los paquetes siguen saliendo a las tiras.",
            .sensitivity: "Sensibilidad", .silenceThreshold: "Umbral de silencio",
            .smoothing: "Suavizado", .bandGrid: "Rejilla de bandas", .windowKind: "Ventana de análisis",
            .aggregation: "Plegado de bandas", .agc: "Ganancia automática",
            .resetDefaults: "Restaurar valores", .autoStart: "Capturar al abrir",
            .autoStartNote: "La app empieza a enviar en cuanto se abre.",
            .sensitivityNote: "Ganancia manual en vez de automática. Útil cuando las tiras respiran en los pasajes suaves.",
            .silenceNote: "Por debajo de este nivel el cuadro se considera vacío y el paquete se apaga.",
            .gridNote: "WLED — la tabla incluida en el firmware, los efectos se hicieron para ella.",
        ],

        .french: [
            .stopped: "Arrêté", .playing: "Le son arrive", .silent: "Silence",
            .noSignal: "Aucun signal", .captureStopped: "Capture arrêtée",
            .start: "Démarrer", .stop: "Arrêter", .quit: "Quitter", .settings: "Réglages",
            .hideSettings: "Masquer les réglages", .diagnostics: "Diagnostic",
            .hideDiagnostics: "Masquer le diagnostic", .copy: "Copier",
            .applyRestart: "Appliquer et redémarrer", .openPrivacy: "Ouvrir les réglages de confidentialité",
            .searchDevices: "Rechercher les rubans", .useFound: "Utiliser les adresses trouvées",
            .addManually: "Ajouter", .refresh: "Actualiser",
            .packetsPerSecond: "paquets/s", .totalPackets: "total", .source: "Source",
            .destination: "Envoi vers", .processing: "Traitement",
            .whereToSend: "Où envoyer", .port: "Port",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Comportement", .launchAtLogin: "Lancer à l’ouverture de session",
            .spectrumInMenuBar: "Spectre dans la barre des menus",
            .originalBehaviour: "Traitement comme l’original",
            .originalBehaviourNote: "Rétablit entièrement le comportement de la version Windows, pour comparer.",
            .language: "Langue", .processingFixed: "amélioré",
            .processingOriginal: "comme l’original", .notSet: "non défini",
            .modeTargetList: "Liste d’adresses", .modeBroadcastLAN: "Diffusion sur le réseau",
            .modeBroadcastSubnet: "Diffusion sur le sous-réseau", .modeMulticast: "Multidiffusion",
            .devices: "Rubans", .noDevicesFound: "Rien trouvé pour l’instant",
            .searchingDevices: "Recherche…", .deviceIdle: "attend un signal",
            .deviceReceiving: "reçoit de nous", .deviceNotReceiving: "ne reçoit pas",
            .deviceUnknown: "pas encore interrogé",
            .manualAddressPlaceholder: "Adresse du ruban",
            .welcomeTitle: "Le spectre du son sur vos rubans",
            .welcomeBody: "Le système demandera deux autorisations : enregistrer l’audio système et accéder au réseau local. L’audio ne sort pas d’ici : seuls 44 octets de spectre par trame sont envoyés.",
            .permissionTitle: "L’audio est lu, mais il ne contient que des zéros",
            .permissionBody: "Cela signifie généralement que l’autorisation d’enregistrer l’audio système n’a pas été accordée.",
            .diagSystemAudio: "Audio système", .diagProcessing: "Traitement",
            .diagSending: "Envoi", .diagDevices: "Rubans",
            .diagOK: "correct", .diagWarning: "attention", .diagFailure: "ne fonctionne pas",
            .diagUnknown: "inconnu", .diagNotRunning: "à l’arrêt",
            .diagAllZeroes: "que des zéros depuis %@ s",
            .diagPermissionAdvice: "L’autorisation d’enregistrer l’audio système manque probablement",
            .diagBandsFlowing: "les bandes se remplissent", .diagBandsEmpty: "toutes les bandes à zéro",
            .diagBandsEmptyAdvice: "Soit c’est silencieux, soit le signal n’atteint pas l’analyse",
            .diagNoTargets: "aucune adresse définie",
            .diagNoTargetsAdvice: "Indiquez les adresses des rubans ou choisissez un mode de diffusion",
            .diagNetworkAdvice: "Vérifiez que le Mac est sur le même réseau que les rubans",
            .diagNotSending: "les paquets ne partent pas",
            .diagAppearsAfterStart: "apparaît après le démarrage",
            .captureRestarted: "Capture reconstruite",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ paq/s vers %@ adr.",
            .diagDevicesUnchecked: "état non vérifié",
            .diagDevicesAdvice: "Lance une recherche de rubans pour les vérifier",
            .diagTitle: "Auralis — diagnostic",
            .columnColour: "Couleur des barres", .animationOn: "Animation activée",
            .animationOff: "Animation désactivée", .quality: "Qualité",
            .qualityFull: "Complète", .qualityLight: "Légère",
            .resetColour: "Réinitialiser",
            .tabLook: "Aspect", .fromPalette: "de la palette",
            .animationOffNote: "La scène n’est plus dessinée. Les paquets continuent vers les rubans.",
            .sensitivity: "Sensibilité", .silenceThreshold: "Seuil de silence",
            .smoothing: "Lissage", .bandGrid: "Grille de bandes", .windowKind: "Fenêtre d’analyse",
            .aggregation: "Repliement des bandes", .agc: "Gain automatique",
            .resetDefaults: "Valeurs par défaut", .autoStart: "Capturer au lancement",
            .autoStartNote: "L’app commence à envoyer dès son ouverture.",
            .sensitivityNote: "Gain manuel au lieu d’automatique. Utile quand les rubans respirent dans les passages calmes.",
            .silenceNote: "Sous ce niveau la trame est vide et le paquet s’éteint.",
            .gridNote: "WLED — la table du firmware, les effets ont été dessinés pour elle.",
        ],

        .arabic: [
            .stopped: "متوقف", .playing: "الصوت يصل", .silent: "صمت",
            .noSignal: "لا إشارة", .captureStopped: "توقف الالتقاط",
            .start: "تشغيل", .stop: "إيقاف", .quit: "إنهاء", .settings: "الإعدادات",
            .hideSettings: "إخفاء الإعدادات", .diagnostics: "التشخيص",
            .hideDiagnostics: "إخفاء التشخيص", .copy: "نسخ",
            .applyRestart: "تطبيق وإعادة التشغيل", .openPrivacy: "فتح إعدادات الخصوصية",
            .searchDevices: "البحث عن الشرائط", .useFound: "استخدام العناوين المكتشفة",
            .addManually: "إضافة", .refresh: "تحديث",
            .packetsPerSecond: "حزمة/ث", .totalPackets: "الإجمالي", .source: "المصدر",
            .destination: "الإرسال إلى", .processing: "المعالجة",
            .whereToSend: "إلى أين نرسل", .port: "المنفذ",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "السلوك", .launchAtLogin: "التشغيل عند تسجيل الدخول",
            .spectrumInMenuBar: "الطيف في شريط القوائم",
            .originalBehaviour: "المعالجة كما في الأصل",
            .originalBehaviourNote: "يعيد سلوك نسخة ويندوز بالكامل — للمقارنة.",
            .language: "اللغة", .processingFixed: "محسّنة",
            .processingOriginal: "كما في الأصل", .notSet: "غير محدد",
            .modeTargetList: "قائمة العناوين", .modeBroadcastLAN: "بث إلى الشبكة",
            .modeBroadcastSubnet: "بث إلى الشبكة الفرعية", .modeMulticast: "بث متعدد",
            .devices: "الشرائط", .noDevicesFound: "لم يُعثر على شيء بعد",
            .searchingDevices: "جارٍ البحث…", .deviceIdle: "بانتظار الإشارة",
            .deviceReceiving: "تستقبل منا", .deviceNotReceiving: "لا تستقبل",
            .deviceUnknown: "لم يتم السؤال بعد",
            .manualAddressPlaceholder: "عنوان الشريط",
            .welcomeTitle: "طيف الصوت إلى الشرائط",
            .welcomeBody: "سيطلب النظام إذنين: تسجيل صوت النظام والوصول إلى الشبكة المحلية. الصوت نفسه لا يُرسل — تُرسل 44 بايت فقط من الطيف لكل إطار.",
            .permissionTitle: "يُقرأ الصوت لكنه أصفار فقط",
            .permissionBody: "عادةً يعني ذلك أن إذن تسجيل صوت النظام لم يُمنح.",
            .diagSystemAudio: "صوت النظام", .diagProcessing: "المعالجة",
            .diagSending: "الإرسال", .diagDevices: "الشرائط",
            .diagOK: "سليم", .diagWarning: "انتبه", .diagFailure: "لا يعمل",
            .diagUnknown: "غير معروف", .diagNotRunning: "غير مُشغَّل",
            .diagAllZeroes: "أصفار فقط منذ %@ ث",
            .diagPermissionAdvice: "الأرجح أن إذن تسجيل صوت النظام لم يُمنح",
            .diagBandsFlowing: "النطاقات تمتلئ", .diagBandsEmpty: "كل النطاقات أصفار",
            .diagBandsEmptyAdvice: "إما أن المكان هادئ، أو أن الإشارة لا تصل إلى التحليل",
            .diagNoTargets: "لا عناوين محددة",
            .diagNoTargetsAdvice: "أدخل عناوين الشرائط أو اختر وضع البث",
            .diagNetworkAdvice: "تأكد أن الماك على نفس شبكة الشرائط",
            .diagNotSending: "الحزم لا تُرسل",
            .diagAppearsAfterStart: "يظهر بعد التشغيل",
            .captureRestarted: "أُعيد بناء الالتقاط",
            .diagSource: "%@، %@ هرتز", .diagSendingRate: "%@ حزمة/ث إلى %@ عنوان",
            .diagDevicesUnchecked: "الحالة غير مفحوصة",
            .diagDevicesAdvice: "ابحث عن الأشرطة لفحصها",
            .diagTitle: "Auralis — التشخيص",
            .columnColour: "لون الأعمدة", .animationOn: "الحركة مفعّلة",
            .animationOff: "الحركة متوقفة", .quality: "الجودة",
            .qualityFull: "كاملة", .qualityLight: "خفيفة",
            .resetColour: "إعادة تعيين",
            .tabLook: "المظهر", .fromPalette: "من اللوحة",
            .animationOffNote: "لا يُرسم المشهد. تستمر الحزم في الذهاب إلى الأشرطة.",
            .sensitivity: "الحساسية", .silenceThreshold: "عتبة الصمت",
            .smoothing: "التنعيم", .bandGrid: "شبكة النطاقات", .windowKind: "نافذة التحليل",
            .aggregation: "طي النطاقات", .agc: "كسب تلقائي",
            .resetDefaults: "استعادة الافتراضي", .autoStart: "بدء الالتقاط عند التشغيل",
            .autoStartNote: "يبدأ التطبيق بالإرسال فور فتحه.",
            .sensitivityNote: "كسب يدوي بدل التلقائي. مفيد عندما تتنفس الأشرطة في المقاطع الهادئة.",
            .silenceNote: "تحت هذا المستوى يُعد الإطار فارغًا وتخبو الحزمة.",
            .gridNote: "WLED — الجدول المدمج في البرنامج الثابت، وقد صُممت المؤثرات له.",
        ],

        .bengali: [
            .stopped: "বন্ধ", .playing: "শব্দ আসছে", .silent: "নীরবতা",
            .noSignal: "সংকেত নেই", .captureStopped: "ক্যাপচার বন্ধ",
            .start: "চালু করুন", .stop: "থামান", .quit: "প্রস্থান", .settings: "সেটিংস",
            .hideSettings: "সেটিংস লুকান", .diagnostics: "ডায়াগনস্টিকস",
            .hideDiagnostics: "ডায়াগনস্টিকস লুকান", .copy: "কপি",
            .applyRestart: "প্রয়োগ করে পুনরায় চালু করুন", .openPrivacy: "গোপনীয়তা সেটিংস খুলুন",
            .searchDevices: "স্ট্রিপ খুঁজুন", .useFound: "পাওয়া ঠিকানা ব্যবহার করুন",
            .addManually: "যোগ করুন", .refresh: "রিফ্রেশ",
            .packetsPerSecond: "প্যাকেট/সে", .totalPackets: "মোট", .source: "উৎস",
            .destination: "পাঠানো হচ্ছে", .processing: "প্রক্রিয়াকরণ",
            .whereToSend: "কোথায় পাঠাবে", .port: "পোর্ট",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "আচরণ", .launchAtLogin: "লগইনে চালু করুন",
            .spectrumInMenuBar: "মেনু বারে স্পেকট্রাম",
            .originalBehaviour: "মূল সংস্করণের মতো প্রক্রিয়াকরণ",
            .originalBehaviourNote: "তুলনার জন্য Windows সংস্করণের আচরণ সম্পূর্ণ ফিরিয়ে আনে।",
            .language: "ভাষা", .processingFixed: "উন্নত",
            .processingOriginal: "মূলের মতো", .notSet: "নির্ধারিত নয়",
            .modeTargetList: "ঠিকানার তালিকা", .modeBroadcastLAN: "নেটওয়ার্কে ব্রডকাস্ট",
            .modeBroadcastSubnet: "সাবনেটে ব্রডকাস্ট", .modeMulticast: "মাল্টিকাস্ট",
            .devices: "স্ট্রিপ", .noDevicesFound: "এখনো কিছু পাওয়া যায়নি",
            .searchingDevices: "খোঁজা হচ্ছে…", .deviceIdle: "সংকেতের অপেক্ষায়",
            .deviceReceiving: "আমাদের থেকে নিচ্ছে", .deviceNotReceiving: "নিচ্ছে না",
            .deviceUnknown: "এখনো জিজ্ঞাসা করা হয়নি",
            .manualAddressPlaceholder: "স্ট্রিপের ঠিকানা",
            .welcomeTitle: "শব্দের স্পেকট্রাম স্ট্রিপে",
            .welcomeBody: "সিস্টেম দুটি অনুমতি চাইবে: সিস্টেম শব্দ রেকর্ড এবং লোকাল নেটওয়ার্ক। শব্দ কোথাও পাঠানো হয় না — প্রতি ফ্রেমে কেবল ৪৪ বাইট স্পেকট্রাম যায়।",
            .permissionTitle: "শব্দ পড়া হচ্ছে, কিন্তু সবই শূন্য",
            .permissionBody: "সাধারণত এর মানে সিস্টেম শব্দ রেকর্ডের অনুমতি দেওয়া হয়নি।",
            .diagSystemAudio: "সিস্টেম শব্দ", .diagProcessing: "প্রক্রিয়াকরণ",
            .diagSending: "পাঠানো", .diagDevices: "স্ট্রিপ",
            .diagOK: "ঠিক আছে", .diagWarning: "লক্ষ্য করুন", .diagFailure: "কাজ করছে না",
            .diagUnknown: "অজানা", .diagNotRunning: "চালু নেই",
            .diagAllZeroes: "%@ সেকেন্ড ধরে সবই শূন্য",
            .diagPermissionAdvice: "সম্ভবত সিস্টেম শব্দ রেকর্ডের অনুমতি দেওয়া হয়নি",
            .diagBandsFlowing: "ব্যান্ড ভরছে", .diagBandsEmpty: "সব ব্যান্ড শূন্য",
            .diagBandsEmptyAdvice: "হয় এখন নীরব, নয়তো সংকেত বিশ্লেষণে পৌঁছাচ্ছে না",
            .diagNoTargets: "কোনো ঠিকানা নেই",
            .diagNoTargetsAdvice: "স্ট্রিপের ঠিকানা দিন বা ব্রডকাস্ট মোড বাছুন",
            .diagNetworkAdvice: "Mac ও স্ট্রিপ একই নেটওয়ার্কে আছে কিনা দেখুন",
            .diagNotSending: "প্যাকেট যাচ্ছে না",
            .diagAppearsAfterStart: "চালু করার পরে দেখা যাবে",
            .captureRestarted: "ক্যাপচার পুনর্গঠিত",
            .diagSource: "%@, %@ হার্টজ", .diagSendingRate: "%@ প্যাকেট/সে %@ ঠিকানায়",
            .diagDevicesUnchecked: "অবস্থা যাচাই করা হয়নি",
            .diagDevicesAdvice: "যাচাই করতে স্ট্রিপ খুঁজুন",
            .diagTitle: "Auralis — নির্ণয়",
            .columnColour: "কলামের রং", .animationOn: "অ্যানিমেশন চালু",
            .animationOff: "অ্যানিমেশন বন্ধ", .quality: "মান",
            .qualityFull: "পূর্ণ", .qualityLight: "হালকা",
            .resetColour: "রিসেট",
            .tabLook: "চেহারা", .fromPalette: "প্যালেট থেকে",
            .animationOffNote: "দৃশ্য আঁকা হচ্ছে না। প্যাকেট স্ট্রিপে যেতেই থাকে।",
            .sensitivity: "সংবেদনশীলতা", .silenceThreshold: "নীরবতার সীমা",
            .smoothing: "স্মুদিং", .bandGrid: "ব্যান্ড গ্রিড", .windowKind: "বিশ্লেষণ উইন্ডো",
            .aggregation: "ব্যান্ড ভাঁজ", .agc: "স্বয়ংক্রিয় গেইন",
            .resetDefaults: "ডিফল্ট ফেরান", .autoStart: "চালু হলেই ক্যাপচার",
            .autoStartNote: "অ্যাপ খোলামাত্র পাঠানো শুরু করে।",
            .sensitivityNote: "স্বয়ংক্রিয়ের বদলে ম্যানুয়াল গেইন। শান্ত অংশে স্ট্রিপ শ্বাস নিলে কাজে লাগে।",
            .silenceNote: "এই স্তরের নিচে ফ্রেম খালি ধরা হয় ও প্যাকেট নিভে যায়।",
            .gridNote: "WLED — ফার্মওয়্যারের নিজস্ব তালিকা, ইফেক্ট তারই জন্য আঁকা।",
        ],

        .portuguese: [
            .stopped: "Parado", .playing: "O som está chegando", .silent: "Silêncio",
            .noSignal: "Sem sinal", .captureStopped: "Captura parada",
            .start: "Iniciar", .stop: "Parar", .quit: "Sair", .settings: "Ajustes",
            .hideSettings: "Ocultar ajustes", .diagnostics: "Diagnóstico",
            .hideDiagnostics: "Ocultar diagnóstico", .copy: "Copiar",
            .applyRestart: "Aplicar e reiniciar", .openPrivacy: "Abrir ajustes de privacidade",
            .searchDevices: "Procurar fitas", .useFound: "Usar endereços encontrados",
            .addManually: "Adicionar", .refresh: "Atualizar",
            .packetsPerSecond: "pacotes/s", .totalPackets: "total", .source: "Fonte",
            .destination: "Enviando para", .processing: "Processamento",
            .whereToSend: "Para onde enviar", .port: "Porta",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Comportamento", .launchAtLogin: "Abrir ao iniciar sessão",
            .spectrumInMenuBar: "Espectro na barra de menus",
            .originalBehaviour: "Processamento como no original",
            .originalBehaviourNote: "Restaura por completo o comportamento da versão Windows — para comparar.",
            .language: "Idioma", .processingFixed: "aprimorado",
            .processingOriginal: "como no original", .notSet: "não definido",
            .modeTargetList: "Lista de endereços", .modeBroadcastLAN: "Difusão na rede",
            .modeBroadcastSubnet: "Difusão na sub-rede", .modeMulticast: "Multicast",
            .devices: "Fitas", .noDevicesFound: "Nada encontrado ainda",
            .searchingDevices: "Procurando…", .deviceIdle: "aguardando sinal",
            .deviceReceiving: "recebendo de nós", .deviceNotReceiving: "não recebe",
            .deviceUnknown: "ainda não consultado",
            .manualAddressPlaceholder: "Endereço da fita",
            .welcomeTitle: "O espectro do som nas suas fitas",
            .welcomeBody: "O sistema pedirá duas permissões: gravar o áudio do sistema e acessar a rede local. O áudio não sai daqui — só 44 bytes de espectro por quadro são enviados.",
            .permissionTitle: "O áudio é lido, mas só tem zeros",
            .permissionBody: "Normalmente significa que a permissão para gravar o áudio do sistema não foi concedida.",
            .diagSystemAudio: "Áudio do sistema", .diagProcessing: "Processamento",
            .diagSending: "Envio", .diagDevices: "Fitas",
            .diagOK: "em ordem", .diagWarning: "atenção", .diagFailure: "não funciona",
            .diagUnknown: "desconhecido", .diagNotRunning: "não está em execução",
            .diagAllZeroes: "só zeros há %@ s",
            .diagPermissionAdvice: "Provavelmente falta a permissão para gravar o áudio do sistema",
            .diagBandsFlowing: "as bandas estão preenchendo", .diagBandsEmpty: "todas as bandas em zero",
            .diagBandsEmptyAdvice: "Ou está silencioso agora, ou o sinal não chega à análise",
            .diagNoTargets: "sem endereços definidos",
            .diagNoTargetsAdvice: "Informe os endereços das fitas ou escolha um modo de difusão",
            .diagNetworkAdvice: "Verifique se o Mac está na mesma rede das fitas",
            .diagNotSending: "os pacotes não saem",
            .diagAppearsAfterStart: "aparece após iniciar",
            .captureRestarted: "Captura reconstruída",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ pac/s para %@ end.",
            .diagDevicesUnchecked: "estado não verificado",
            .diagDevicesAdvice: "Procure fitas para verificá-las",
            .diagTitle: "Auralis — diagnóstico",
            .columnColour: "Cor das barras", .animationOn: "Animação ligada",
            .animationOff: "Animação desligada", .quality: "Qualidade",
            .qualityFull: "Completa", .qualityLight: "Leve",
            .resetColour: "Redefinir",
            .tabLook: "Aparência", .fromPalette: "da paleta",
            .animationOffNote: "A cena não é desenhada. Os pacotes continuam indo às fitas.",
            .sensitivity: "Sensibilidade", .silenceThreshold: "Limiar de silêncio",
            .smoothing: "Suavização", .bandGrid: "Grade de bandas", .windowKind: "Janela de análise",
            .aggregation: "Dobra de bandas", .agc: "Ganho automático",
            .resetDefaults: "Restaurar padrões", .autoStart: "Capturar ao abrir",
            .autoStartNote: "O app começa a enviar assim que abre.",
            .sensitivityNote: "Ganho manual em vez de automático. Útil quando as fitas respiram nos trechos calmos.",
            .silenceNote: "Abaixo deste nível o quadro é vazio e o pacote se apaga.",
            .gridNote: "WLED — a tabela do firmware, os efeitos foram feitos para ela.",
        ],

        .urdu: [
            .stopped: "رکا ہوا", .playing: "آواز آ رہی ہے", .silent: "خاموشی",
            .noSignal: "کوئی سگنل نہیں", .captureStopped: "کیپچر رک گیا",
            .start: "شروع کریں", .stop: "روکیں", .quit: "بند کریں", .settings: "ترتیبات",
            .hideSettings: "ترتیبات چھپائیں", .diagnostics: "تشخیص",
            .hideDiagnostics: "تشخیص چھپائیں", .copy: "کاپی",
            .applyRestart: "لاگو کریں اور دوبارہ چلائیں", .openPrivacy: "پرائیویسی ترتیبات کھولیں",
            .searchDevices: "سٹرپس تلاش کریں", .useFound: "ملے ہوئے پتے استعمال کریں",
            .addManually: "شامل کریں", .refresh: "تازہ کریں",
            .packetsPerSecond: "پیکٹ/سیکنڈ", .totalPackets: "کل", .source: "ماخذ",
            .destination: "بھیجا جا رہا ہے", .processing: "پروسیسنگ",
            .whereToSend: "کہاں بھیجیں", .port: "پورٹ",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "رویہ", .launchAtLogin: "لاگ اِن پر چلائیں",
            .spectrumInMenuBar: "مینو بار میں سپیکٹرم",
            .originalBehaviour: "اصل جیسی پروسیسنگ",
            .originalBehaviourNote: "موازنے کے لیے Windows ورژن کا رویہ مکمل بحال کرتا ہے۔",
            .language: "زبان", .processingFixed: "بہتر",
            .processingOriginal: "اصل جیسا", .notSet: "مقرر نہیں",
            .modeTargetList: "پتوں کی فہرست", .modeBroadcastLAN: "نیٹ ورک پر براڈکاسٹ",
            .modeBroadcastSubnet: "سب نیٹ پر براڈکاسٹ", .modeMulticast: "ملٹی کاسٹ",
            .devices: "سٹرپس", .noDevicesFound: "ابھی کچھ نہیں ملا",
            .searchingDevices: "تلاش جاری…", .deviceIdle: "سگنل کا انتظار",
            .deviceReceiving: "ہم سے وصول کر رہی ہے", .deviceNotReceiving: "وصول نہیں کر رہی",
            .deviceUnknown: "ابھی پوچھا نہیں",
            .manualAddressPlaceholder: "سٹرپ کا پتہ",
            .welcomeTitle: "آواز کا سپیکٹرم سٹرپس پر",
            .welcomeBody: "سسٹم دو اجازتیں مانگے گا: سسٹم آواز ریکارڈ کرنا اور مقامی نیٹ ورک۔ آواز کہیں نہیں بھیجی جاتی — فی فریم صرف 44 بائٹ سپیکٹرم جاتا ہے۔",
            .permissionTitle: "آواز پڑھی جا رہی ہے مگر اس میں صرف صفر ہیں",
            .permissionBody: "عام طور پر اس کا مطلب ہے کہ سسٹم آواز ریکارڈ کرنے کی اجازت نہیں دی گئی۔",
            .diagSystemAudio: "سسٹم آواز", .diagProcessing: "پروسیسنگ",
            .diagSending: "بھیجنا", .diagDevices: "سٹرپس",
            .diagOK: "ٹھیک", .diagWarning: "توجہ", .diagFailure: "کام نہیں کر رہا",
            .diagUnknown: "نامعلوم", .diagNotRunning: "چل نہیں رہا",
            .diagAllZeroes: "%@ سیکنڈ سے صرف صفر",
            .diagPermissionAdvice: "غالباً سسٹم آواز کی اجازت نہیں دی گئی",
            .diagBandsFlowing: "بینڈ بھر رہے ہیں", .diagBandsEmpty: "تمام بینڈ صفر",
            .diagBandsEmptyAdvice: "یا تو ابھی خاموشی ہے، یا سگنل تجزیے تک نہیں پہنچ رہا",
            .diagNoTargets: "کوئی پتہ مقرر نہیں",
            .diagNoTargetsAdvice: "سٹرپس کے پتے درج کریں یا براڈکاسٹ موڈ چنیں",
            .diagNetworkAdvice: "دیکھیں کہ Mac اور سٹرپس ایک ہی نیٹ ورک پر ہیں",
            .diagNotSending: "پیکٹ نہیں جا رہے",
            .diagAppearsAfterStart: "شروع کرنے پر ظاہر ہوگا",
            .captureRestarted: "کیپچر دوبارہ بنایا گیا",
            .diagSource: "%@، %@ ہرٹز", .diagSendingRate: "%@ پیکٹ/سیکنڈ %@ پتوں پر",
            .diagDevicesUnchecked: "حالت جانچی نہیں گئی",
            .diagDevicesAdvice: "جانچنے کے لیے سٹرپس تلاش کریں",
            .diagTitle: "Auralis — تشخیص",
            .columnColour: "کالم کا رنگ", .animationOn: "اینیمیشن آن",
            .animationOff: "اینیمیشن آف", .quality: "معیار",
            .qualityFull: "مکمل", .qualityLight: "ہلکا",
            .resetColour: "ری سیٹ",
            .tabLook: "ظاہری شکل", .fromPalette: "پیلیٹ سے",
            .animationOffNote: "منظر نہیں بن رہا۔ پیکٹ سٹرپس کو جاتے رہتے ہیں۔",
            .sensitivity: "حساسیت", .silenceThreshold: "خاموشی کی حد",
            .smoothing: "ہمواری", .bandGrid: "بینڈ گرڈ", .windowKind: "تجزیہ ونڈو",
            .aggregation: "بینڈ تہہ", .agc: "خودکار گین",
            .resetDefaults: "ڈیفالٹ بحال کریں", .autoStart: "شروع ہوتے ہی کیپچر",
            .autoStartNote: "ایپ کھلتے ہی بھیجنا شروع کر دیتی ہے۔",
            .sensitivityNote: "خودکار کی بجائے دستی گین۔ جب پُرسکون حصوں میں سٹرپ سانس لے تو مفید۔",
            .silenceNote: "اس سطح سے نیچے فریم خالی سمجھا جاتا ہے اور پیکٹ مدھم ہو جاتا ہے۔",
            .gridNote: "WLED — فرم ویئر کی اپنی جدول، ایفیکٹس اسی کے لیے بنے۔",
        ],

        .indonesian: [
            .stopped: "Berhenti", .playing: "Ada suara", .silent: "Sunyi",
            .noSignal: "Tidak ada sinyal", .captureStopped: "Perekaman berhenti",
            .start: "Mulai", .stop: "Hentikan", .quit: "Keluar", .settings: "Pengaturan",
            .hideSettings: "Sembunyikan pengaturan", .diagnostics: "Diagnostik",
            .hideDiagnostics: "Sembunyikan diagnostik", .copy: "Salin",
            .applyRestart: "Terapkan dan mulai ulang", .openPrivacy: "Buka pengaturan privasi",
            .searchDevices: "Cari strip", .useFound: "Pakai alamat yang ditemukan",
            .addManually: "Tambah", .refresh: "Segarkan",
            .packetsPerSecond: "paket/dtk", .totalPackets: "total", .source: "Sumber",
            .destination: "Dikirim ke", .processing: "Pemrosesan",
            .whereToSend: "Kirim ke mana", .port: "Porta",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Perilaku", .launchAtLogin: "Jalankan saat masuk",
            .spectrumInMenuBar: "Spektrum di bilah menu",
            .originalBehaviour: "Pemrosesan seperti aslinya",
            .originalBehaviourNote: "Mengembalikan perilaku versi Windows sepenuhnya — untuk perbandingan.",
            .language: "Bahasa", .processingFixed: "diperbaiki",
            .processingOriginal: "seperti aslinya", .notSet: "belum diatur",
            .modeTargetList: "Daftar alamat", .modeBroadcastLAN: "Siaran ke jaringan",
            .modeBroadcastSubnet: "Siaran ke subnet", .modeMulticast: "Multicast",
            .devices: "Strip", .noDevicesFound: "Belum ada yang ditemukan",
            .searchingDevices: "Mencari…", .deviceIdle: "menunggu sinyal",
            .deviceReceiving: "menerima dari kita", .deviceNotReceiving: "tidak menerima",
            .deviceUnknown: "belum ditanya",
            .manualAddressPlaceholder: "Alamat strip",
            .welcomeTitle: "Spektrum suara ke strip LED",
            .welcomeBody: "Sistem akan meminta dua izin: merekam suara sistem dan akses jaringan lokal. Suaranya sendiri tidak dikirim ke mana pun — hanya 44 bita spektrum per bingkai.",
            .permissionTitle: "Suara terbaca, tetapi isinya nol semua",
            .permissionBody: "Biasanya itu berarti izin merekam suara sistem belum diberikan.",
            .diagSystemAudio: "Suara sistem", .diagProcessing: "Pemrosesan",
            .diagSending: "Pengiriman", .diagDevices: "Strip",
            .diagOK: "baik", .diagWarning: "perhatian", .diagFailure: "tidak bekerja",
            .diagUnknown: "tidak diketahui", .diagNotRunning: "tidak berjalan",
            .diagAllZeroes: "nol semua selama %@ dtk",
            .diagPermissionAdvice: "Kemungkinan besar izin merekam suara sistem belum diberikan",
            .diagBandsFlowing: "pita terisi", .diagBandsEmpty: "semua pita nol",
            .diagBandsEmptyAdvice: "Entah sekarang memang sunyi, atau sinyal tidak sampai ke analisis",
            .diagNoTargets: "alamat belum diatur",
            .diagNoTargetsAdvice: "Masukkan alamat strip atau pilih mode siaran",
            .diagNetworkAdvice: "Pastikan Mac berada di jaringan yang sama dengan strip",
            .diagNotSending: "paket tidak terkirim",
            .diagAppearsAfterStart: "muncul setelah dimulai",
            .captureRestarted: "Perekaman dibangun ulang",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ paket/dtk ke %@ alamat",
            .diagDevicesUnchecked: "status belum diperiksa",
            .diagDevicesAdvice: "Cari strip untuk memeriksanya",
            .diagTitle: "Auralis — diagnostik",
            .columnColour: "Warna batang", .animationOn: "Animasi aktif",
            .animationOff: "Animasi mati", .quality: "Kualitas",
            .qualityFull: "Penuh", .qualityLight: "Ringan",
            .resetColour: "Atur ulang",
            .tabLook: "Tampilan", .fromPalette: "dari palet",
            .animationOffNote: "Adegan tidak digambar. Paket tetap dikirim ke strip.",
            .sensitivity: "Sensitivitas", .silenceThreshold: "Ambang senyap",
            .smoothing: "Penghalusan", .bandGrid: "Kisi pita", .windowKind: "Jendela analisis",
            .aggregation: "Pelipatan pita", .agc: "Penguatan otomatis",
            .resetDefaults: "Kembalikan bawaan", .autoStart: "Rekam saat dibuka",
            .autoStartNote: "Aplikasi mulai mengirim begitu dibuka.",
            .sensitivityNote: "Penguatan manual, bukan otomatis. Berguna saat strip bernapas di bagian tenang.",
            .silenceNote: "Di bawah level ini bingkai dianggap kosong dan paket meredup.",
            .gridNote: "WLED — tabel bawaan firmware, efek dirancang untuknya.",
        ],

        .german: [
            .stopped: "Gestoppt", .playing: "Ton kommt an", .silent: "Stille",
            .noSignal: "Kein Signal", .captureStopped: "Aufnahme gestoppt",
            .start: "Starten", .stop: "Stoppen", .quit: "Beenden", .settings: "Einstellungen",
            .hideSettings: "Einstellungen ausblenden", .diagnostics: "Diagnose",
            .hideDiagnostics: "Diagnose ausblenden", .copy: "Kopieren",
            .applyRestart: "Übernehmen und neu starten", .openPrivacy: "Datenschutzeinstellungen öffnen",
            .searchDevices: "Streifen suchen", .useFound: "Gefundene Adressen übernehmen",
            .addManually: "Hinzufügen", .refresh: "Aktualisieren",
            .packetsPerSecond: "Pakete/s", .totalPackets: "gesamt", .source: "Quelle",
            .destination: "Senden an", .processing: "Verarbeitung",
            .whereToSend: "Wohin senden", .port: "Port",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Verhalten", .launchAtLogin: "Bei der Anmeldung starten",
            .spectrumInMenuBar: "Spektrum in der Menüleiste",
            .originalBehaviour: "Verarbeitung wie im Original",
            .originalBehaviourNote: "Stellt das Verhalten der Windows-Version vollständig wieder her — zum Vergleich.",
            .language: "Sprache", .processingFixed: "verbessert",
            .processingOriginal: "wie im Original", .notSet: "nicht gesetzt",
            .modeTargetList: "Adressliste", .modeBroadcastLAN: "Broadcast ins Netz",
            .modeBroadcastSubnet: "Broadcast ins Subnetz", .modeMulticast: "Multicast",
            .devices: "Streifen", .noDevicesFound: "Noch nichts gefunden",
            .searchingDevices: "Suche läuft…", .deviceIdle: "wartet auf Signal",
            .deviceReceiving: "empfängt von uns", .deviceNotReceiving: "empfängt nicht",
            .deviceUnknown: "noch nicht abgefragt",
            .manualAddressPlaceholder: "Adresse des Streifens",
            .welcomeTitle: "Klangspektrum auf die Streifen",
            .welcomeBody: "Das System fragt nach zwei Berechtigungen: Systemton aufnehmen und lokales Netzwerk. Der Ton selbst verlässt den Rechner nicht — es gehen nur 44 Byte Spektrum pro Bild hinaus.",
            .permissionTitle: "Ton wird gelesen, enthält aber nur Nullen",
            .permissionBody: "Meist bedeutet das, dass die Berechtigung zum Aufnehmen des Systemtons fehlt.",
            .diagSystemAudio: "Systemton", .diagProcessing: "Verarbeitung",
            .diagSending: "Senden", .diagDevices: "Streifen",
            .diagOK: "in Ordnung", .diagWarning: "Achtung", .diagFailure: "funktioniert nicht",
            .diagUnknown: "unbekannt", .diagNotRunning: "läuft nicht",
            .diagAllZeroes: "seit %@ s nur Nullen",
            .diagPermissionAdvice: "Vermutlich fehlt die Berechtigung zum Aufnehmen des Systemtons",
            .diagBandsFlowing: "Bänder füllen sich", .diagBandsEmpty: "alle Bänder auf null",
            .diagBandsEmptyAdvice: "Entweder ist es gerade still, oder das Signal erreicht die Analyse nicht",
            .diagNoTargets: "keine Adressen gesetzt",
            .diagNoTargetsAdvice: "Adressen der Streifen eintragen oder einen Broadcast-Modus wählen",
            .diagNetworkAdvice: "Prüfen, ob der Mac im selben Netz wie die Streifen ist",
            .diagNotSending: "es gehen keine Pakete hinaus",
            .diagAppearsAfterStart: "erscheint nach dem Start",
            .captureRestarted: "Aufnahme neu aufgebaut",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ Pak/s an %@ Adr.",
            .diagDevicesUnchecked: "Zustand nicht geprüft",
            .diagDevicesAdvice: "Suche nach Streifen, um sie zu prüfen",
            .diagTitle: "Auralis — Diagnose",
            .columnColour: "Farbe der Balken", .animationOn: "Animation an",
            .animationOff: "Animation aus", .quality: "Qualität",
            .qualityFull: "Voll", .qualityLight: "Leicht",
            .resetColour: "Zurücksetzen",
            .tabLook: "Aussehen", .fromPalette: "aus der Palette",
            .animationOffNote: "Die Szene wird nicht gezeichnet. Pakete gehen weiter an die Streifen.",
            .sensitivity: "Empfindlichkeit", .silenceThreshold: "Stilleschwelle",
            .smoothing: "Glättung", .bandGrid: "Bandraster", .windowKind: "Analysefenster",
            .aggregation: "Bandfaltung", .agc: "Automatische Verstärkung",
            .resetDefaults: "Standard wiederherstellen", .autoStart: "Beim Start aufnehmen",
            .autoStartNote: "Die App sendet sofort nach dem Öffnen.",
            .sensitivityNote: "Manuelle statt automatischer Verstärkung. Nützlich, wenn die Streifen in leisen Passagen atmen.",
            .silenceNote: "Unter diesem Pegel gilt der Rahmen als leer und das Paket blendet aus.",
            .gridNote: "WLED — die Tabelle aus der Firmware, die Effekte wurden dafür gezeichnet.",
        ],

        .ukrainian: [
            .stopped: "Зупинено", .playing: "Звук іде", .silent: "Тиша",
            .noSignal: "Немає сигналу", .captureStopped: "Захоплення зупинено",
            .start: "Запустити", .stop: "Зупинити", .quit: "Вийти", .settings: "Налаштування",
            .hideSettings: "Сховати налаштування", .diagnostics: "Діагностика",
            .hideDiagnostics: "Сховати діагностику", .copy: "Скопіювати",
            .applyRestart: "Застосувати й перезапустити", .openPrivacy: "Відкрити налаштування приватності",
            .searchDevices: "Шукати стрічки", .useFound: "Підставити знайдені",
            .addManually: "Додати", .refresh: "Оновити",
            .packetsPerSecond: "пакетів/с", .totalPackets: "усього", .source: "Джерело",
            .destination: "Надсилання", .processing: "Обробка",
            .whereToSend: "Куди надсилати", .port: "Порт",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Поведінка", .launchAtLogin: "Запускати під час входу",
            .spectrumInMenuBar: "Спектр у рядку меню",
            .originalBehaviour: "Обробка як в оригіналі",
            .originalBehaviourNote: "Повертає поведінку Windows-версії повністю — для порівняння.",
            .language: "Мова", .processingFixed: "виправлена",
            .processingOriginal: "як в оригіналі", .notSet: "не задано",
            .modeTargetList: "Списком адрес", .modeBroadcastLAN: "Broadcast у мережу",
            .modeBroadcastSubnet: "Broadcast у підмережу", .modeMulticast: "Multicast",
            .devices: "Стрічки", .noDevicesFound: "Поки не знайдено",
            .searchingDevices: "Триває пошук…", .deviceIdle: "чекає на сигнал",
            .deviceReceiving: "приймає від нас", .deviceNotReceiving: "не приймає",
            .deviceUnknown: "ще не питали",
            .manualAddressPlaceholder: "Адреса стрічки",
            .welcomeTitle: "Спектр звуку — на стрічки",
            .welcomeBody: "Система попросить два дозволи: на запис системного звуку й на доступ до локальної мережі. Сам звук нікуди не передається — у мережу йдуть лише 44 байти спектра на кадр.",
            .permissionTitle: "Звук читається, але в ньому самі нулі",
            .permissionBody: "Зазвичай це означає, що не надано дозвіл на запис системного звуку.",
            .diagSystemAudio: "Системний звук", .diagProcessing: "Обробка",
            .diagSending: "Надсилання", .diagDevices: "Стрічки",
            .diagOK: "гаразд", .diagWarning: "увага", .diagFailure: "не працює",
            .diagUnknown: "невідомо", .diagNotRunning: "не запущено",
            .diagAllZeroes: "самі нулі вже %@ с",
            .diagPermissionAdvice: "Найімовірніше не надано дозвіл на запис системного звуку",
            .diagBandsFlowing: "смуги заповнюються", .diagBandsEmpty: "усі смуги нульові",
            .diagBandsEmptyAdvice: "Або зараз тиша, або сигнал не доходить до аналізу",
            .diagNoTargets: "адресатів не задано",
            .diagNoTargetsAdvice: "Вкажи адреси стрічок або обери широкомовний режим",
            .diagNetworkAdvice: "Перевір, що мак у тій самій мережі, що й стрічки",
            .diagNotSending: "пакети не йдуть",
            .diagAppearsAfterStart: "з’явиться після запуску",
            .captureRestarted: "Захоплення перезібрано",
            .diagSource: "%@, %@ Гц", .diagSendingRate: "%@ пак/с на %@ адр.",
            .diagDevicesUnchecked: "стан не перевірявся",
            .diagDevicesAdvice: "Запусти пошук стрічок, щоб їх перевірити",
            .diagTitle: "Auralis — діагностика",
            .columnColour: "Колір стовпчиків", .animationOn: "Анімацію увімкнено",
            .animationOff: "Анімацію вимкнено", .quality: "Якість",
            .qualityFull: "Повна", .qualityLight: "Легка",
            .resetColour: "Скинути",
            .tabLook: "Вигляд", .fromPalette: "з палітри",
            .animationOffNote: "Сцена не малюється. Пакети продовжують іти на стрічки.",
            .sensitivity: "Чутливість", .silenceThreshold: "Поріг тиші",
            .smoothing: "Згладжування", .bandGrid: "Сітка смуг", .windowKind: "Вікно аналізу",
            .aggregation: "Згортка смуг", .agc: "Авторегулювання",
            .resetDefaults: "Повернути рекомендовані", .autoStart: "Запускати захоплення одразу",
            .autoStartNote: "Застосунок починає надсилання одразу після відкриття.",
            .sensitivityNote: "Ручне підсилення замість автоматичного. Потрібне, коли стрічка дихає на тихих місцях.",
            .silenceNote: "Нижче цього рівня кадр вважається порожнім і пакет згасає.",
            .gridNote: "WLED — таблиця з самої прошивки, ефекти малювалися під неї.",
        ],

        .italian: [
            .stopped: "Fermo", .playing: "Il suono arriva", .silent: "Silenzio",
            .noSignal: "Nessun segnale", .captureStopped: "Acquisizione ferma",
            .start: "Avvia", .stop: "Ferma", .quit: "Esci", .settings: "Impostazioni",
            .hideSettings: "Nascondi impostazioni", .diagnostics: "Diagnostica",
            .hideDiagnostics: "Nascondi diagnostica", .copy: "Copia",
            .applyRestart: "Applica e riavvia", .openPrivacy: "Apri impostazioni privacy",
            .searchDevices: "Cerca strisce", .useFound: "Usa gli indirizzi trovati",
            .addManually: "Aggiungi", .refresh: "Aggiorna",
            .packetsPerSecond: "pacchetti/s", .totalPackets: "totale", .source: "Sorgente",
            .destination: "Invio a", .processing: "Elaborazione",
            .whereToSend: "Dove inviare", .port: "Porta",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Comportamento", .launchAtLogin: "Avvia all’accesso",
            .spectrumInMenuBar: "Spettro nella barra dei menu",
            .originalBehaviour: "Elaborazione come nell’originale",
            .originalBehaviourNote: "Ripristina per intero il comportamento della versione Windows — per confronto.",
            .language: "Lingua", .processingFixed: "migliorata",
            .processingOriginal: "come l’originale", .notSet: "non impostato",
            .modeTargetList: "Elenco di indirizzi", .modeBroadcastLAN: "Broadcast in rete",
            .modeBroadcastSubnet: "Broadcast nella sottorete", .modeMulticast: "Multicast",
            .devices: "Strisce", .noDevicesFound: "Ancora nulla",
            .searchingDevices: "Ricerca in corso…", .deviceIdle: "in attesa di segnale",
            .deviceReceiving: "riceve da noi", .deviceNotReceiving: "non riceve",
            .deviceUnknown: "non ancora interrogata",
            .manualAddressPlaceholder: "Indirizzo della striscia",
            .welcomeTitle: "Lo spettro del suono sulle strisce",
            .welcomeBody: "Il sistema chiederà due autorizzazioni: registrare l’audio di sistema e accedere alla rete locale. L’audio non esce da qui: si inviano solo 44 byte di spettro per fotogramma.",
            .permissionTitle: "L’audio viene letto, ma contiene solo zeri",
            .permissionBody: "Di solito significa che non è stata concessa l’autorizzazione a registrare l’audio di sistema.",
            .diagSystemAudio: "Audio di sistema", .diagProcessing: "Elaborazione",
            .diagSending: "Invio", .diagDevices: "Strisce",
            .diagOK: "a posto", .diagWarning: "attenzione", .diagFailure: "non funziona",
            .diagUnknown: "sconosciuto", .diagNotRunning: "non in esecuzione",
            .diagAllZeroes: "solo zeri da %@ s",
            .diagPermissionAdvice: "Probabilmente manca l’autorizzazione a registrare l’audio di sistema",
            .diagBandsFlowing: "le bande si riempiono", .diagBandsEmpty: "tutte le bande a zero",
            .diagBandsEmptyAdvice: "O adesso c’è silenzio, o il segnale non arriva all’analisi",
            .diagNoTargets: "nessun indirizzo impostato",
            .diagNoTargetsAdvice: "Inserisci gli indirizzi delle strisce o scegli una modalità broadcast",
            .diagNetworkAdvice: "Verifica che il Mac sia sulla stessa rete delle strisce",
            .diagNotSending: "i pacchetti non partono",
            .diagAppearsAfterStart: "compare dopo l’avvio",
            .captureRestarted: "Acquisizione ricostruita",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ pacch/s a %@ ind.",
            .diagDevicesUnchecked: "stato non verificato",
            .diagDevicesAdvice: "Cerca le strisce per verificarle",
            .diagTitle: "Auralis — diagnostica",
            .columnColour: "Colore delle barre", .animationOn: "Animazione attiva",
            .animationOff: "Animazione disattivata", .quality: "Qualità",
            .qualityFull: "Completa", .qualityLight: "Leggera",
            .resetColour: "Ripristina",
            .tabLook: "Aspetto", .fromPalette: "dalla palette",
            .animationOffNote: "La scena non viene disegnata. I pacchetti continuano ad andare alle strisce.",
            .sensitivity: "Sensibilità", .silenceThreshold: "Soglia di silenzio",
            .smoothing: "Smorzamento", .bandGrid: "Griglia delle bande", .windowKind: "Finestra di analisi",
            .aggregation: "Ripiegamento bande", .agc: "Guadagno automatico",
            .resetDefaults: "Ripristina predefiniti", .autoStart: "Cattura all’avvio",
            .autoStartNote: "L’app inizia a inviare appena si apre.",
            .sensitivityNote: "Guadagno manuale invece che automatico. Utile quando le strisce respirano nei passaggi quieti.",
            .silenceNote: "Sotto questo livello il frame è vuoto e il pacchetto sfuma.",
            .gridNote: "WLED — la tabella del firmware, gli effetti sono nati per quella.",
        ],

        .swedish: [
            .stopped: "Stoppad", .playing: "Ljud kommer in", .silent: "Tystnad",
            .noSignal: "Ingen signal", .captureStopped: "Inspelning stoppad",
            .start: "Starta", .stop: "Stoppa", .quit: "Avsluta", .settings: "Inställningar",
            .hideSettings: "Dölj inställningar", .diagnostics: "Diagnostik",
            .hideDiagnostics: "Dölj diagnostik", .copy: "Kopiera",
            .applyRestart: "Tillämpa och starta om", .openPrivacy: "Öppna integritetsinställningar",
            .searchDevices: "Sök efter slingor", .useFound: "Använd hittade adresser",
            .addManually: "Lägg till", .refresh: "Uppdatera",
            .packetsPerSecond: "paket/s", .totalPackets: "totalt", .source: "Källa",
            .destination: "Skickar till", .processing: "Bearbetning",
            .whereToSend: "Vart ska det skickas", .port: "Port",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Beteende", .launchAtLogin: "Starta vid inloggning",
            .spectrumInMenuBar: "Spektrum i menyraden",
            .originalBehaviour: "Bearbetning som i originalet",
            .originalBehaviourNote: "Återställer Windows-versionens beteende helt — för jämförelse.",
            .language: "Språk", .processingFixed: "förbättrad",
            .processingOriginal: "som originalet", .notSet: "inte angivet",
            .modeTargetList: "Adresslista", .modeBroadcastLAN: "Broadcast till nätet",
            .modeBroadcastSubnet: "Broadcast till subnätet", .modeMulticast: "Multicast",
            .devices: "Slingor", .noDevicesFound: "Inget hittat ännu",
            .searchingDevices: "Söker…", .deviceIdle: "väntar på signal",
            .deviceReceiving: "tar emot från oss", .deviceNotReceiving: "tar inte emot",
            .deviceUnknown: "inte tillfrågad ännu",
            .manualAddressPlaceholder: "Slingans adress",
            .welcomeTitle: "Ljudets spektrum till slingorna",
            .welcomeBody: "Systemet frågar efter två behörigheter: spela in systemljud och nå det lokala nätverket. Ljudet självt lämnar inte datorn — bara 44 byte spektrum per bildruta skickas.",
            .permissionTitle: "Ljudet läses, men innehåller bara nollor",
            .permissionBody: "Det brukar betyda att behörigheten att spela in systemljud inte har getts.",
            .diagSystemAudio: "Systemljud", .diagProcessing: "Bearbetning",
            .diagSending: "Sändning", .diagDevices: "Slingor",
            .diagOK: "i ordning", .diagWarning: "obs", .diagFailure: "fungerar inte",
            .diagUnknown: "okänt", .diagNotRunning: "körs inte",
            .diagAllZeroes: "bara nollor sedan %@ s",
            .diagPermissionAdvice: "Troligen saknas behörigheten att spela in systemljud",
            .diagBandsFlowing: "banden fylls", .diagBandsEmpty: "alla band är noll",
            .diagBandsEmptyAdvice: "Antingen är det tyst nu, eller så når signalen inte fram till analysen",
            .diagNoTargets: "inga adresser angivna",
            .diagNoTargetsAdvice: "Ange slingornas adresser eller välj ett broadcast-läge",
            .diagNetworkAdvice: "Kontrollera att datorn är på samma nät som slingorna",
            .diagNotSending: "paketen skickas inte",
            .diagAppearsAfterStart: "visas efter start",
            .captureRestarted: "Inspelningen byggdes om",
            .diagSource: "%@, %@ Hz", .diagSendingRate: "%@ paket/s till %@ adr.",
            .diagDevicesUnchecked: "tillstånd ej kontrollerat",
            .diagDevicesAdvice: "Sök efter slingor för att kontrollera dem",
            .diagTitle: "Auralis — diagnostik",
            .columnColour: "Färg på staplarna", .animationOn: "Animation på",
            .animationOff: "Animation av", .quality: "Kvalitet",
            .qualityFull: "Full", .qualityLight: "Lätt",
            .resetColour: "Återställ",
            .tabLook: "Utseende", .fromPalette: "från paletten",
            .animationOffNote: "Scenen ritas inte. Paketen fortsätter till slingorna.",
            .sensitivity: "Känslighet", .silenceThreshold: "Tystnadströskel",
            .smoothing: "Utjämning", .bandGrid: "Bandrutnät", .windowKind: "Analysfönster",
            .aggregation: "Bandvikning", .agc: "Automatisk förstärkning",
            .resetDefaults: "Återställ standard", .autoStart: "Fånga vid start",
            .autoStartNote: "Appen börjar sända så snart den öppnas.",
            .sensitivityNote: "Manuell förstärkning i stället för automatisk. Bra när slingorna andas i tysta partier.",
            .silenceNote: "Under denna nivå räknas bildrutan som tom och paketet tonar ut.",
            .gridNote: "WLED — tabellen från firmware, effekterna ritades för den.",
        ],

        .belarusian: [
            .stopped: "Спынена", .playing: "Гук ідзе", .silent: "Цішыня",
            .noSignal: "Няма сігналу", .captureStopped: "Захоп спынены",
            .start: "Запусціць", .stop: "Спыніць", .quit: "Выйсці", .settings: "Налады",
            .hideSettings: "Схаваць налады", .diagnostics: "Дыягностыка",
            .hideDiagnostics: "Схаваць дыягностыку", .copy: "Скапіяваць",
            .applyRestart: "Ужыць і перазапусціць", .openPrivacy: "Адкрыць налады прыватнасці",
            .searchDevices: "Шукаць стужкі", .useFound: "Падставіць знойдзеныя",
            .addManually: "Дадаць", .refresh: "Абнавіць",
            .packetsPerSecond: "пакетаў/с", .totalPackets: "усяго", .source: "Крыніца",
            .destination: "Адпраўка", .processing: "Апрацоўка",
            .whereToSend: "Куды адпраўляць", .port: "Порт",
            .targetsPlaceholder: "192.168.1.50, 192.168.1.51",
            .behaviour: "Паводзіны", .launchAtLogin: "Запускаць пры ўваходзе",
            .spectrumInMenuBar: "Спектр у радку меню",
            .originalBehaviour: "Апрацоўка як у арыгінале",
            .originalBehaviourNote: "Вяртае паводзіны Windows-версіі цалкам — для параўнання.",
            .language: "Мова", .processingFixed: "выпраўленая",
            .processingOriginal: "як у арыгінале", .notSet: "не зададзена",
            .modeTargetList: "Спісам адрасоў", .modeBroadcastLAN: "Broadcast у сетку",
            .modeBroadcastSubnet: "Broadcast у падсетку", .modeMulticast: "Multicast",
            .devices: "Стужкі", .noDevicesFound: "Пакуль не знойдзена",
            .searchingDevices: "Ідзе пошук…", .deviceIdle: "чакае сігналу",
            .deviceReceiving: "прымае ад нас", .deviceNotReceiving: "не прымае",
            .deviceUnknown: "яшчэ не пыталіся",
            .manualAddressPlaceholder: "Адрас стужкі",
            .welcomeTitle: "Спектр гуку — на стужкі",
            .welcomeBody: "Сістэма папросіць два дазволы: на запіс сістэмнага гуку і на доступ да лакальнай сеткі. Сам гук нікуды не перадаецца — у сетку ідуць толькі 44 байты спектру на кадр.",
            .permissionTitle: "Гук чытаецца, але ў ім адны нулі",
            .permissionBody: "Звычайна гэта азначае, што не выдадзены дазвол на запіс сістэмнага гуку.",
            .diagSystemAudio: "Сістэмны гук", .diagProcessing: "Апрацоўка",
            .diagSending: "Адпраўка", .diagDevices: "Стужкі",
            .diagOK: "у парадку", .diagWarning: "увага", .diagFailure: "не працуе",
            .diagUnknown: "невядома", .diagNotRunning: "не запушчана",
            .diagAllZeroes: "адны нулі ўжо %@ с",
            .diagPermissionAdvice: "Хутчэй за ўсё не выдадзены дазвол на запіс сістэмнага гуку",
            .diagBandsFlowing: "палосы запаўняюцца", .diagBandsEmpty: "усе палосы нулявыя",
            .diagBandsEmptyAdvice: "Або зараз цішыня, або сігнал не даходзіць да аналізу",
            .diagNoTargets: "адрасаты не зададзены",
            .diagNoTargetsAdvice: "Пазнач адрасы стужак або абяры шырокавяшчальны рэжым",
            .diagNetworkAdvice: "Праверце, што мак у той жа сетцы, што і стужкі",
            .diagNotSending: "пакеты не ідуць",
            .diagAppearsAfterStart: "з’явіцца пасля запуску",
            .captureRestarted: "Захоп перазабраны",
            .diagSource: "%@, %@ Гц", .diagSendingRate: "%@ пак/с на %@ адр.",
            .diagDevicesUnchecked: "стан не правяраўся",
            .diagDevicesAdvice: "Запусці пошук стужак, каб іх праверыць",
            .diagTitle: "Auralis — дыягностыка",
            .columnColour: "Колер слупкоў", .animationOn: "Анімацыя ўключана",
            .animationOff: "Анімацыя выключана", .quality: "Якасць",
            .qualityFull: "Поўная", .qualityLight: "Лёгкая",
            .resetColour: "Скінуць",
            .tabLook: "Выгляд", .fromPalette: "з палітры",
            .animationOffNote: "Сцэна не малюецца. Пакеты працягваюць ісці на стужкі.",
            .sensitivity: "Адчувальнасць", .silenceThreshold: "Парог цішыні",
            .smoothing: "Згладжванне", .bandGrid: "Сетка палос", .windowKind: "Акно аналізу",
            .aggregation: "Згортка палос", .agc: "Аўтарэгуляванне",
            .resetDefaults: "Вярнуць рэкамендаваныя", .autoStart: "Запускаць захоп адразу",
            .autoStartNote: "Праграма пачынае адпраўку адразу пасля адкрыцця.",
            .sensitivityNote: "Ручное ўзмацненне замест аўтаматычнага. Патрэбна, калі стужка дыхае на цiхіх месцах.",
            .silenceNote: "Ніжэй за гэты ўзровень кадр лічыцца пустым і пакет згасае.",
            .gridNote: "WLED — табліца з самой прашыўкі, эфекты малявалiся пад яе.",
        ],
    ]
}
